# Generated by Django 4.2.1 on 2023-06-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='products',
            field=models.CharField(default=1, max_length=77),
            preserve_default=False,
        ),
    ]
