# Generated by Django 4.2.1 on 2023-06-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordering',
            name='products',
        ),
    ]
